# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160121_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='backgrounds/'),
        ),
    ]
