# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('profiles', '0003_auto_20160122_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_series',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='series.Series'),
        ),
    ]
