# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_subscribed_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/backgrounds/'),
        ),
    ]
