# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160311_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
