# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160312_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
