# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_user_youtube_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube_player',
            field=models.BooleanField(default=False),
        ),
    ]
