# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160311_1357'),
        ('profiles', '0009_user_youtube_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to='comments.Comment'),
        ),
    ]
