# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160917_0252'),
        ('profiles', '0010_user_comments_upvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to='posts.Post'),
        ),
    ]
