# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='backgrounds/'),
        ),
    ]
