# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='series/'),
        ),
    ]
