# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20160125_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='series/avatars/'),
        ),
    ]
