# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
        ('series', '0005_auto_20160311_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='hubs',
            field=models.ManyToManyField(blank=True, related_name='series', to='hubs.Hub'),
        ),
    ]
