* Poses
Poses are the key thing in animation. They tell the story.


- Every image has to be an illustration.

  
# Express emotion
- Pose reveals the character. Pose is not a symptom of a movement.  
  Movement is a symptom of character's emotional state. 
  phose is primary mechanism of telling the story.

Foundation of animation.

# Express personality

# Easy to understand
Appeal and emotion.
- Appeal - easy to read and understand what he's thinking and feeling.
lear and easy to read with one glance

# //Tells a story

# Sihlouette
Cg is not 3d. it's 2d.
think of it like a painting.
2d shapes.
look through camera.
from 2d standpoint.

- Great poses, even though they're still, have motion in them.
  
  
# Line of action
drive eyes
flow of lines.
line through character's body indicating direction and energy of the pose.

- Reversal of line of action
buid up and release of energy.



# Exaggeration!

# Assymetry!

# Weight
shift weight to one leg
think on center of gravity!

think of physics. things and body parts are heavy.

chest tilts in the opposite direction of pelvis.
http://www.animatorisland.com/perfect-posing-1-listen-to-the-character-and-to-physics/
# Volume

Mountains.
Rhythm.
Variety.
smaller, accents.

choose the biggest most important pose of the scene.


# Flow lines
All parts of the character create visual flow.
direct viewer's eye.
drive focus.

> best poses draw eye to what audience is supposed to look at.
scene composition thing.
direct to what's important.

# curved vs straight!
https://support.animationmentor.com/hc/en-us/community/posts/200964893-Posing-Silhouette-and-Line-of-Action-References

# tips
tilt the head
twist the torso

# Good composition. staging.

# Don't force animation princples.
dont' do sihlouette for sihlouette sake.
don't break flow lines or fuck up other stuff by trying to adhere to some one principle.
keep poses clean and simple.

# body - 3 circles. not in one line.

# closed/open
introverted/extraverted.
