# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160311_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to='videos.Video'),
        ),
    ]
