# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160917_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dvblog',
            field=models.BooleanField(default=False),
        ),
    ]
