# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
        ('videos', '0003_auto_20160311_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hub',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='hubs.Hub'),
        ),
    ]
