# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
        ('videos', '0005_auto_20160312_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hubs',
        ),
        migrations.AddField(
            model_name='video',
            name='hubs',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='videos', to='hubs.Hub'),
        ),
    ]
