# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20160312_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='digitalverse',
            field=models.BooleanField(default=False),
        ),
    ]
