# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=videos.models.generate_filename),
        ),
    ]
