# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160310_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
