# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_hub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='hub',
            new_name='hubs',
        ),
    ]
