# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_digitalverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hubs',
            field=models.ManyToManyField(blank=True, default=None, related_name='videos', to='hubs.Hub'),
        ),
    ]
